first_num = int(input("First number : "))
second_num = int(input("Second number : "))
print("Addition :",first_num + second_num)
print("Substraction :",first_num - second_num)
print("Multipliaction :",first_num * second_num)
print("Division:",first_num / second_num)
print("Exponential :",first_num ** second_num)
print("Thank you!!")
